/* This file is generated by v2/scripts/media/generate_ascii_video_registry.py. */
export interface AsciiVideoVariant {
  id: string;
  label: string;
  eyebrow: string;
  title: string;
  videoSrc: string;
  posterSrc: string;
  subtitlesSrc: string;
  subtitlesDownloadSrc?: string;
  soundtrackSrc: string;
  scriptSrc?: string;
  aspect: 'vertical' | 'wide';
}

export interface AsciiVideoConfig {
  title: string;
  variants: AsciiVideoVariant[];
}

export const ASCII_VIDEOS: Record<string, AsciiVideoConfig> = {
  "aprender-para-ser-libres-la-educacin-como-acto-de-soberana": {
    "title": "Aprender para Ser Libres: La Educación como Acto de Soberanía",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 6:20 · sello cruz orlada",
        "title": "Aprender para Ser Libres: La Educación como Acto de Soberanía",
        "videoSrc": "/media/ascii-videos/aprender-para-ser-libres-la-educacin-como-acto-de-soberana/aprender-para-ser-libres-la-educacin-como-acto-de-soberana-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/aprender-para-ser-libres-la-educacin-como-acto-de-soberana/aprender-para-ser-libres-la-educacin-como-acto-de-soberana-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/aprender-para-ser-libres-la-educacin-como-acto-de-soberana/aprender-para-ser-libres-la-educacin-como-acto-de-soberana-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/aprender-para-ser-libres-la-educacin-como-acto-de-soberana/aprender-para-ser-libres-la-educacin-como-acto-de-soberana-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/aprender-para-ser-libres-la-educacin-como-acto-de-soberana/aprender-para-ser-libres-la-educacin-como-acto-de-soberana-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/aprender-para-ser-libres-la-educacin-como-acto-de-soberana/aprender-para-ser-libres-la-educacin-como-acto-de-soberana-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "buscar-en-el-pasado-para-controlar-el-futuro": {
    "title": "Buscar en el pasado para controlar el futuro",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 21:45 · sello cruz orlada",
        "title": "Buscar en el pasado para controlar el futuro",
        "videoSrc": "/media/ascii-videos/buscar-en-el-pasado-para-controlar-el-futuro/buscar-en-el-pasado-para-controlar-el-futuro-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/buscar-en-el-pasado-para-controlar-el-futuro/buscar-en-el-pasado-para-controlar-el-futuro-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/buscar-en-el-pasado-para-controlar-el-futuro/buscar-en-el-pasado-para-controlar-el-futuro-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/buscar-en-el-pasado-para-controlar-el-futuro/buscar-en-el-pasado-para-controlar-el-futuro-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/buscar-en-el-pasado-para-controlar-el-futuro/buscar-en-el-pasado-para-controlar-el-futuro-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/buscar-en-el-pasado-para-controlar-el-futuro/buscar-en-el-pasado-para-controlar-el-futuro-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar": {
    "title": "Detectar Patrones: Otro Poder Que Ya Tenés y Nadie Te Enseñó a Usar",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 16:50 · sello cruz orlada",
        "title": "Detectar Patrones: Otro Poder Que Ya Tenés y Nadie Te Enseñó a Usar",
        "videoSrc": "/media/ascii-videos/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar/detectar-patrones-otro-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "diseo-idealizado-la-argentina-posible": {
    "title": "Diseño Idealizado: La Argentina Posible",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 4:57 · sello cruz orlada",
        "title": "Diseño Idealizado: La Argentina Posible",
        "videoSrc": "/media/ascii-videos/diseo-idealizado-la-argentina-posible/diseo-idealizado-la-argentina-posible-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/diseo-idealizado-la-argentina-posible/diseo-idealizado-la-argentina-posible-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/diseo-idealizado-la-argentina-posible/diseo-idealizado-la-argentina-posible-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/diseo-idealizado-la-argentina-posible/diseo-idealizado-la-argentina-posible-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/diseo-idealizado-la-argentina-posible/diseo-idealizado-la-argentina-posible-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/diseo-idealizado-la-argentina-posible/diseo-idealizado-la-argentina-posible-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "el-abrazo-que-no-supimos-sostener": {
    "title": "El abrazo que no supimos sostener",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 16:39 · sello cruz orlada",
        "title": "El abrazo que no supimos sostener",
        "videoSrc": "/media/ascii-videos/el-abrazo-que-no-supimos-sostener/el-abrazo-que-no-supimos-sostener-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/el-abrazo-que-no-supimos-sostener/el-abrazo-que-no-supimos-sostener-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/el-abrazo-que-no-supimos-sostener/el-abrazo-que-no-supimos-sostener-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/el-abrazo-que-no-supimos-sostener/el-abrazo-que-no-supimos-sostener-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/el-abrazo-que-no-supimos-sostener/el-abrazo-que-no-supimos-sostener-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/el-abrazo-que-no-supimos-sostener/el-abrazo-que-no-supimos-sostener-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "el-cansancio-sagrado-por-qu-ya-no-podemos-esperar": {
    "title": "El Cansancio Sagrado: Por qué ya no podemos esperar",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 5:35 · sello cruz orlada",
        "title": "El Cansancio Sagrado: Por qué ya no podemos esperar",
        "videoSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-mobile-full-full-script.md",
        "aspect": "vertical"
      },
      {
        "id": "short-wide",
        "label": "Short 16:9",
        "eyebrow": "16:9 · 0:42 · resumen",
        "title": "El Cansancio Sagrado: Por qué ya no podemos esperar",
        "videoSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-ascii.mp4",
        "posterSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-ascii-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-ascii.vtt",
        "soundtrackSrc": "/media/ascii-videos/el-cansancio-sagrado/el-cansancio-sagrado-soundtrack.mp3",
        "aspect": "wide"
      }
    ]
  },
  "el-cristo-que-llevs-dentro": {
    "title": "El Cristo que llevás dentro",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 19:18 · sello cruz orlada",
        "title": "El Cristo que llevás dentro",
        "videoSrc": "/media/ascii-videos/el-cristo-que-llevs-dentro/el-cristo-que-llevs-dentro-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/el-cristo-que-llevs-dentro/el-cristo-que-llevs-dentro-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/el-cristo-que-llevs-dentro/el-cristo-que-llevs-dentro-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/el-cristo-que-llevs-dentro/el-cristo-que-llevs-dentro-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/el-cristo-que-llevs-dentro/el-cristo-que-llevs-dentro-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/el-cristo-que-llevs-dentro/el-cristo-que-llevs-dentro-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "el-poder-del-pensamiento-sistmico-en-la-transformacin-social": {
    "title": "El Poder del Pensamiento Sistémico en la Transformación Social",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 4:22 · sello cruz orlada",
        "title": "El Poder del Pensamiento Sistémico en la Transformación Social",
        "videoSrc": "/media/ascii-videos/el-poder-del-pensamiento-sistmico-en-la-transformacin-social/el-poder-del-pensamiento-sistmico-en-la-transformacin-social-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/el-poder-del-pensamiento-sistmico-en-la-transformacin-social/el-poder-del-pensamiento-sistmico-en-la-transformacin-social-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/el-poder-del-pensamiento-sistmico-en-la-transformacin-social/el-poder-del-pensamiento-sistmico-en-la-transformacin-social-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/el-poder-del-pensamiento-sistmico-en-la-transformacin-social/el-poder-del-pensamiento-sistmico-en-la-transformacin-social-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/el-poder-del-pensamiento-sistmico-en-la-transformacin-social/el-poder-del-pensamiento-sistmico-en-la-transformacin-social-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/el-poder-del-pensamiento-sistmico-en-la-transformacin-social/el-poder-del-pensamiento-sistmico-en-la-transformacin-social-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos": {
    "title": "Inteligencia Colectiva: Por Qué Juntos Pensamos Mejor de lo que Creemos",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 5:39 · sello cruz orlada",
        "title": "Inteligencia Colectiva: Por Qué Juntos Pensamos Mejor de lo que Creemos",
        "videoSrc": "/media/ascii-videos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos/inteligencia-colectiva-por-qu-juntos-pensamos-mejor-de-lo-que-creemos-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "la-amabilidad-como-estrategia-de-transformacin": {
    "title": "La Amabilidad como Estrategia de Transformación",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 3:16 · sello cruz orlada",
        "title": "La Amabilidad como Estrategia de Transformación",
        "videoSrc": "/media/ascii-videos/la-amabilidad-como-estrategia-de-transformacin/la-amabilidad-como-estrategia-de-transformacin-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/la-amabilidad-como-estrategia-de-transformacin/la-amabilidad-como-estrategia-de-transformacin-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/la-amabilidad-como-estrategia-de-transformacin/la-amabilidad-como-estrategia-de-transformacin-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/la-amabilidad-como-estrategia-de-transformacin/la-amabilidad-como-estrategia-de-transformacin-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/la-amabilidad-como-estrategia-de-transformacin/la-amabilidad-como-estrategia-de-transformacin-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/la-amabilidad-como-estrategia-de-transformacin/la-amabilidad-como-estrategia-de-transformacin-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "la-amabilidad-como-ingeniera-social": {
    "title": "La Amabilidad como Ingeniería Social",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 4:19 · sello cruz orlada",
        "title": "La Amabilidad como Ingeniería Social",
        "videoSrc": "/media/ascii-videos/la-amabilidad-como-ingeniera-social/la-amabilidad-como-ingeniera-social-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/la-amabilidad-como-ingeniera-social/la-amabilidad-como-ingeniera-social-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/la-amabilidad-como-ingeniera-social/la-amabilidad-como-ingeniera-social-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/la-amabilidad-como-ingeniera-social/la-amabilidad-como-ingeniera-social-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/la-amabilidad-como-ingeniera-social/la-amabilidad-como-ingeniera-social-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/la-amabilidad-como-ingeniera-social/la-amabilidad-como-ingeniera-social-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "la-ciencia-de-la-confianza-el-capital-que-nadie-mide-pero-todos-necesitan": {
    "title": "La Ciencia de la Confianza: El Capital que Nadie Mide pero Todos Necesitan",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 5:58 · sello cruz orlada",
        "title": "La Ciencia de la Confianza: El Capital que Nadie Mide pero Todos Necesitan",
        "videoSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-full-script.md",
        "aspect": "vertical"
      },
      {
        "id": "seal-test",
        "label": "Sello ASCII",
        "eyebrow": "9:16 · 5:29 · prueba cruz orlada",
        "title": "La Ciencia de la Confianza: El Capital que Nadie Mide pero Todos Necesitan",
        "videoSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-seal-test.mp4",
        "posterSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-seal-test-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/la-ciencia-de-la-confianza/la-ciencia-de-la-confianza-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "la-tica-del-servicio-construyendo-una-sociedad-de-servidores": {
    "title": "La Ética del Servicio: Construyendo una Sociedad de Servidores",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 4:38 · sello cruz orlada",
        "title": "La Ética del Servicio: Construyendo una Sociedad de Servidores",
        "videoSrc": "/media/ascii-videos/la-tica-del-servicio-construyendo-una-sociedad-de-servidores/la-tica-del-servicio-construyendo-una-sociedad-de-servidores-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/la-tica-del-servicio-construyendo-una-sociedad-de-servidores/la-tica-del-servicio-construyendo-una-sociedad-de-servidores-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/la-tica-del-servicio-construyendo-una-sociedad-de-servidores/la-tica-del-servicio-construyendo-una-sociedad-de-servidores-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/la-tica-del-servicio-construyendo-una-sociedad-de-servidores/la-tica-del-servicio-construyendo-una-sociedad-de-servidores-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/la-tica-del-servicio-construyendo-una-sociedad-de-servidores/la-tica-del-servicio-construyendo-una-sociedad-de-servidores-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/la-tica-del-servicio-construyendo-una-sociedad-de-servidores/la-tica-del-servicio-construyendo-una-sociedad-de-servidores-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar": {
    "title": "Las Fuerzas del Cielo: El Poder que ya Tenés y Nadie te Enseñó a Usar",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 15:54 · sello cruz orlada",
        "title": "Las Fuerzas del Cielo: El Poder que ya Tenés y Nadie te Enseñó a Usar",
        "videoSrc": "/media/ascii-videos/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar/las-fuerzas-del-cielo-el-poder-que-ya-tens-y-nadie-te-ense-a-usar-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo": {
    "title": "Lo Que Le Debemos al Futuro: Responsabilidad Intergeneracional como Diseño",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 5:33 · sello cruz orlada",
        "title": "Lo Que Le Debemos al Futuro: Responsabilidad Intergeneracional como Diseño",
        "videoSrc": "/media/ascii-videos/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo/lo-que-le-debemos-al-futuro-responsabilidad-intergeneracional-como-diseo-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "pago-por-inteligencia-artificial-y-por-la-ma": {
    "title": "Pago por Inteligencia Artificial. ¿Y por la mía?",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 11:51 · sello cruz orlada",
        "title": "Pago por Inteligencia Artificial. ¿Y por la mía?",
        "videoSrc": "/media/ascii-videos/pago-por-inteligencia-artificial-y-por-la-ma/pago-por-inteligencia-artificial-y-por-la-ma-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/pago-por-inteligencia-artificial-y-por-la-ma/pago-por-inteligencia-artificial-y-por-la-ma-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/pago-por-inteligencia-artificial-y-por-la-ma/pago-por-inteligencia-artificial-y-por-la-ma-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/pago-por-inteligencia-artificial-y-por-la-ma/pago-por-inteligencia-artificial-y-por-la-ma-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/pago-por-inteligencia-artificial-y-por-la-ma/pago-por-inteligencia-artificial-y-por-la-ma-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/pago-por-inteligencia-artificial-y-por-la-ma/pago-por-inteligencia-artificial-y-por-la-ma-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin": {
    "title": "Por Qué Nos Resistimos a Cambiar: La Psicología de la Transformación",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 6:15 · sello cruz orlada",
        "title": "Por Qué Nos Resistimos a Cambiar: La Psicología de la Transformación",
        "videoSrc": "/media/ascii-videos/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin/por-qu-nos-resistimos-a-cambiar-la-psicologa-de-la-transformacin-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "quien-tiene-el-timon": {
    "title": "¿Quién tiene el timón?",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 17:09 · sello cruz orlada",
        "title": "¿Quién tiene el timón?",
        "videoSrc": "/media/ascii-videos/quien-tiene-el-timon/quien-tiene-el-timon-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/quien-tiene-el-timon/quien-tiene-el-timon-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/quien-tiene-el-timon/quien-tiene-el-timon-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/quien-tiene-el-timon/quien-tiene-el-timon-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/quien-tiene-el-timon/quien-tiene-el-timon-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/quien-tiene-el-timon/quien-tiene-el-timon-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "refinarse-o-repetirse": {
    "title": "Refinarse o Repetirse",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 14:15 · sello cruz orlada",
        "title": "Refinarse o Repetirse",
        "videoSrc": "/media/ascii-videos/refinarse-o-repetirse/refinarse-o-repetirse-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/refinarse-o-repetirse/refinarse-o-repetirse-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/refinarse-o-repetirse/refinarse-o-repetirse-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/refinarse-o-repetirse/refinarse-o-repetirse-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/refinarse-o-repetirse/refinarse-o-repetirse-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/refinarse-o-repetirse/refinarse-o-repetirse-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  },
  "sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social": {
    "title": "Sistemas vs. Síntomas: Cómo Pensar como Ingeniero Social",
    "variants": [
      {
        "id": "mobile-full",
        "label": "Mobile con sello",
        "eyebrow": "9:16 · 27:40 · sello cruz orlada",
        "title": "Sistemas vs. Síntomas: Cómo Pensar como Ingeniero Social",
        "videoSrc": "/media/ascii-videos/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social-mobile-full.mp4",
        "posterSrc": "/media/ascii-videos/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social-mobile-full-poster.jpg",
        "subtitlesSrc": "/media/ascii-videos/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social-mobile-full.vtt",
        "subtitlesDownloadSrc": "/media/ascii-videos/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social-mobile-full.srt",
        "soundtrackSrc": "/media/ascii-videos/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social-mobile-full-mix.mp3",
        "scriptSrc": "/media/ascii-videos/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social/sistemas-vs-sntomas-cmo-pensar-como-ingeniero-social-mobile-full-full-script.md",
        "aspect": "vertical"
      }
    ]
  }
};
