export const CARTOGRAFIA_HREF_MAP: Record<string, string> = {
  'El Manifiesto del Hombre Gris': '/manifiesto',
  'Manifiesto del Hombre Gris': '/manifiesto',
  'Manifiesto': '/manifiesto',
  'La Visión': '/la-vision',
  'El Mandato Vivo': '/el-mandato-vivo',
  'Mandato Territorial': '/el-mandato-vivo',
  'Mandato Público': '/el-mandato-vivo',
  'La Semilla de ¡BASTA!': '/la-semilla-de-basta',
  'La Semilla': '/la-semilla-de-basta',
  'El Mapa': '/el-mapa',
  'Datos Abiertos': '/explorar-datos',
  'Explorar Datos': '/explorar-datos',
  'Blog': '/recursos/blog',
  'Vlog': '/recursos/vlog',
  'Rutas de Transformación': '/recursos/guias-estudio',
  'Challenges': '/challenges',
  'Una Ruta para Argentina': '/recursos/ruta',
  'Perfil del Hombre Gris': '/el-instante-del-hombre-gris',
  'Persona del Hombre Gris': '/el-instante-del-hombre-gris',
  'Presentación de la Plataforma': '/',
  'La falacia de la democracia': '/recursos/ensayos/democracia',
  'La falacia del poder mismo': '/recursos/ensayos/poder',
  'Una arquitectura para el hombre gris': '/recursos/ensayos/arquitectura',
  'La soberanía del hombre gris': '/recursos/ensayos/soberania',
  'La belleza como acto político': '/recursos/ensayos/belleza',
  'Carta al Nieto': '/recursos/ensayos/carta-al-nieto',
  'La fábrica de obediencia': '/recursos/ensayos/fabrica-obediencia',
  'El caudillo y el camino sin camino': '/recursos/ensayos/caudillo-camino-sin-camino',
  'El miedo y el devenir': '/recursos/ensayos/miedo-y-devenir',
  'La libertad de lo conocido': '/recursos/ensayos/libertad-de-lo-conocido',
  'Conocerse sin espejo': '/recursos/ensayos/conocerse-sin-espejo',
  'El amor sin apego': '/recursos/ensayos/amor-sin-apego',
  'La sensibilidad como infraestructura': '/recursos/ensayos/sensibilidad-como-infraestructura',
};
